#'@title Set up samples of quadrats with high and low intensity
#'@description Divide a set of quadrats into sets with high and low estimated 
#'intensity of a point pattern.
#'The quadrats can either be given, or generated by splitting the window  of the 
#'point pattern into rectangular quadrats.
#'@param pp The point pattern, object of class \code{ppp} or \code{sostyppp}
#'@param quads optional, a tessellation (class \code{tess}) or a list of windows
#'(class \code{owin}) that is to be divided into subsets
#'@param nx,ny number of quadrats in the \code{x} and \code{y} directions
#'@param gradx,grady logical, if \code{TRUE}, the \eqn{x} resp. \eqn{y} coordinates
#'of the pattern \code{pp} are used to determine the boundaries
#'@param xbreaks,ybreaks numeric vector of \eqn{x} resp. \eqn{y} coordinates of the
#'quadrat boundaries
#'@param minpoints minimum number of points required, see Details.
#'@details
#'If \code{quadrats} is not given, the quadrats are generated using spatstat's function 
#'\code{\link{quadrats}}, which splits the window into rectangles.
#'Then, the \eqn{x}-coordinates of quadrat boundaries are determined either by 
#'specifying \code{xbreaks}, or by \code{nx} and \code{gradx}, with priority on \code{xbreaks}. 
#'If \code{gradx} is \code{TRUE}, equidistant quantiles of the 
#'\eqn{x}-coordinates of the point pattern \code{pp} are used; otherwise, 
#'the boundaries are equally spaced. The \eqn{y}-coordinate is treated analogously.
#'
#'Quadrats with a number of points less than \code{minpoints} are returned as
#'a list "\code{unused}". The remaining quadrats are divided into a set with high
#'and a set with low estimated intensity. The median of the intensity estimates
#'on the "used" quadrats serves as threshold.
#'  
#'@return A list with three elements \code{hi}, \code{lo} and \code{unused}. The 
#'elements themselves are lists of spatstat-\code{owin} objects.
#'@seealso The spatstat function \code{quadrats}
#'
#'@export
#'@author Ute Hahn,  \email{ute@@imf.au.dk}


quadsets.hilo <- function (pp, quads = NULL, 
                           nx = NULL, ny = NULL,  gradx = FALSE, grady = FALSE,
                           xbreaks = NULL, ybreaks = NULL,
                           minpoints = 20){
  NULL
}